export {
  FaHome as HomeIcon,
  FaSignInAlt as SignInIcon,
  FaSignOutAlt as SignOutIcon,
  FaPlus as PlusIcon,
  FaTimes as TimesIcon,
  FaCoffee as CoffeeIcon,
  FaFlag as FlagIcon,
  FaThumbsUp as ThumbsUpIcon,
  FaThumbsDown as ThumbsDownIcon,
  FaMinus as MinusIcon,
  FaCheck as CheckIcon,
  FaChevronDown as ChevronDownIcon,
  FaCheckCircle as CheckCircleIcon,
  FaEllipsisV as EllipsisVIcon,
} from 'react-icons/fa';
